// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/bagastri07/be-test-kumparan/models"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// AuthorService is an autogenerated mock type for the AuthorService type
type AuthorService struct {
	mock.Mock
}

// CreateAuthor provides a mock function with given fields: ctx, payload
func (_m *AuthorService) CreateAuthor(ctx context.Context, payload *models.CreateAuthorPayload) error {
	ret := _m.Called(ctx, payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateAuthorPayload) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthorService creates a new instance of AuthorService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthorService(t testing.TB) *AuthorService {
	mock := &AuthorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
